### ISSUE TITLE
Rendering overhaul proposals

### ISSUE THREAD

**Issue by rlaemmel** [softlang/metalib#10]
Here are some proposals for making the rendering results look better.

I don't try to say in each case exactly what should be done, but I am providing some "constraints".

* Sections must be clearly separated. Something as simple as an HR may work.
* "Concrete syntax Feature" -> "Concrete syntax //feature//" Basically, use smaller case for appending feature or features and use different font. I think what you are doing is to generate the HEADLINE from the features when an explicit headline is missing. Well, why not.
* There is just too much tagging going on, maybe we just need to give in and have a table with rows for "Features", "Perspective", "Languages", "Technologies", "Concepts". You could still use the coloring scheme at hand and you could print the categories in small font, but some sort of systematic grouping and labeling appears to be necessary. Otherwise, one just gets lost in this cloud of tags.
* "Undefined Headline" (for contributions) must be rejected by well-formedness checker. We really want a name (a headline).

I add more things as I figure them out.

**Comment by johanneshaertel** [comment]
Point 2 and 4 is related to the way I inserted the models into metalib. Until this point, the rendering needs information to be almost complete. So indeed, I generate missing things in my transformation (headlines when undefined) since I do not want to repeat. Maybe we should include this logic into the rendering.

**Comment by rlaemmel** [comment]
Issue 2:
Yes, we do not want redundancy.
Headline is optional for sections.
So rendering must deal with missing headline in sections.

Issue 4:
Headline is mandatory for contributions.
It must be carefully authored and not generated.
