### ISSUE TITLE
Well-formedness checker in the works?

### ISSUE THREAD

**Issue by rlaemmel** [softlang/metalib#12]
cc @johanneshaertel @MarcelH91 

Is there such a checker already up and running?

Here is a few things:

* Check cardinalities from metamodel? For instance, https://softlang.github.io/metalib/javaInfluentInternal.html lacks currently a headline, even though it is mandatory.

* Ping URLs for concepts, languages, technologies on 101wiki. This needs to be done cleverly, of course, to remember pages that were pinged during the current run or on the same day :-)

* Ping source code URLs on GitHub.

I will add more at some point.

**Comment by rlaemmel** [comment]
I deprioritize this.
We need to get #14 more urgently.

**Comment by le-cram** [comment]
@sschauss : Could you write a quick "how to run" for the checker? 
We could write this in this project's Wiki as well. It's probably good to follow the locality principle and put all important project related additional information at one place.

**Comment by rlaemmel** [comment]
I think this is Ok.
