### ISSUE TITLE
Explicit feature model

### ISSUE THREAD

**Issue by rlaemmel** [softlang/metalib#14]
Let's get started with adding the feature model proper to the repo.

Initially, let's go with this expressiveness only:

<pre>
[
  {
     “feature” : “Parsing”,
     “abstract” : true;
     “super” : “Textual syntax”
  },
  …
]
</pre>

Just this expressiveness will be sufficient to enable some basic checking and rendering as follows:
* Check that all feature names in documentation are actually known.
* Check that "meta" perspective never implements "abstract" features.
* Show abstract features in sort of "dimmed" manner in the tables.
* Infer abstract features from declared concrete features so that they are shown in tables.

**Comment by rlaemmel** [comment]
There are indeed feature names in use that don't exist anymore.
See for example "Creole" ... on the landing page.

**Comment by rlaemmel** [comment]
See also #12 which adds more (possibly less urgent) well-formedness ideas.

**Comment by le-cram** [comment]
https://github.com/softlang/metalib/blob/master/tools/metadocs/feature-model.json
