### ISSUE TITLE
Foldabel

### ISSUE THREAD

**Issue by rlaemmel** [softlang/metalib#2]
Should be Foldable in https://github.com/softlang/metalib/blob/master/rascal/fsml/src/main/rascal/org/softlang/fsml/ConcreteSyntax.rsc
<pre>
start syntax Fsm = @Foldabel fsm: State* states;
</pre>

**Comment by sschauss** [comment]
I will remove the Annotation. There's nothing the states could be folded into.

We would need something like this:

```rascal
start syntax Fsm = @Foldable fsm: Name name "{" State* states "}";
```
