### ISSUE TITLE
Tagclouds on landing page

### ISSUE THREAD

**Issue by rlaemmel** [softlang/metalib#22]
cc @johanneshaertel 

This issue promotes a neglected common on #13 to a proper issue.

(It also adds some detail and motivation.)

We want tagclouds for these entities:

* perspectives
* features
* languages
* technologies
* concepts

These should be shown after the long table on the landing page.

These tagclouds will be useful for renarration, as they give a clear impression of the more important perspectives, features, languages, technologies, and concepts.

The entities in tagclouds should be linked in the same way as per pending #21.
That is, the entities are linked to the synthesized pages on https://softlang.github.io/metalib/

**Comment by rlaemmel** [comment]
We need the tagcloud for concepts for the paper and it needs to look good, i.e., we may need to push the methodology far enough so that the right concepts with some reasonable recurrence show up.

**Comment by sschauss** [comment]
I've added the tag clouds to the landing page, but I don't know what's the best place to put them. Do you have any suggestions ?

**Comment by johanneshaertel** [comment]
I suggest we arrange it comparable to the columns in the tables to keep it consistent. Therefore, the tagclouds need to be tall.

**Comment by rlaemmel** [comment]
They look great, but let's have a nice section structure on the landing page with clear **headings** (captions) and not too much empty space. So use headings like "Perspectives", "Features", and such. Make it simple to visually tell apart the sections. Still a problem with first section (list of impls) versus second section (THE TABLE). Use headers and clear separators and no big space.

**Comment by le-cram** [comment]
This is probably fulfilled now.
