### ISSUE TITLE
Catch up with latest metamodel for doc

### ISSUE THREAD

**Issue by rlaemmel** [softlang/metalib#31]
cc @johanneshaertel 
cc @MarcelH91 

I just committed to paper dir (and YAS for what it matters).

ChangeLog with regard to the metamodel for doc:
* meta -> implementation
* object -> data (to unite it with preexisting data)

BTW, please also make sure to use upper case for names of perspectives in the web view and when linking to 101wiki.

**Comment by rlaemmel** [comment]
Oops. Only now I committed to svn.

**Comment by rlaemmel** [comment]
BTW, just for fun, I mention that enums are now supported in YAS' metamodeling notation.
They are simply desugared to abstract and concrete classes without members.
Tiny rocket science.

**Comment by le-cram** [comment]
We caught up with it as far as I think :-)
