### ISSUE TITLE
Add model javaFluentInternal

### ISSUE THREAD

**Issue by rlaemmel** [softlang/metalib#5]
Section:
https://github.com/softlang/yas/blob/master/languages/FSML/Java/org/softlang/fsml/fluent/Sample.java
Features: Interface (object perspective)
Concepts: Fluent API

Section:
https://github.com/softlang/yas/blob/master/languages/FSML/Java/org/softlang/fsml/fluent/Fsm.java
https://github.com/softlang/yas/blob/master/languages/FSML/Java/org/softlang/fsml/fluent/ActionStatePair.java
Features: Interface
Concepts: Fluent API

This section proposal implies a breaking change to the metamodel and I file a separate issue.
That is, we need to be able to have sections with multiple projections.
Of course, this is not absolutely necessary because we could just have two sections, but this is a good example, where two files must remain together.

Section:
https://github.com/softlang/yas/blob/master/languages/FSML/Java/org/softlang/fsml/fluent/FsmImpl.java
Features: AST+
Concepts: Fluent API
Headline: Implementation of fluent API

Section:
https://github.com/softlang/yas/blob/master/languages/FSML/Java/org/softlang/fsml/fluent/FsmlInterpreter.java
Features: Interpret^O

Section:
https://github.com/softlang/yas/blob/master/languages/FSML/Java/org/softlang/fsml/tests/FluentTest.java
Features: Interpret^O (test perspective)
Technologies: JUnit

**Comment by rlaemmel** [comment]
cc @johanneshaertel 
There is a section missing for actual template processing:
https://github.com/softlang/yas/blob/master/languages/FSML/Java/org/softlang/fsml/FsmlCGenerator.java
This should come before the section for testing template processing.

**Comment by johanneshaertel** [comment]
javaFluentInternal does not contain sections about template processing. Do you mean javaInfluentInternal?

**Comment by johanneshaertel** [comment]
I added this to javaInfluentInternal.
