### ISSUE TITLE
Breaking change to MLDF

### ISSUE THREAD

**Issue by rlaemmel** [softlang/metalib#8]
cc @johanneshaertel @MarcelH91 

I have just changed this:

https://github.com/softlang/yas/blob/master/languages/MLDF/mm.mml

Not a big deal I hope, but it needs to be addressed.

The proposed models #6 and #5 depend on this change.

Rationale: It happens that several files must be shown together. For instance, when an object model is implemented in Java in several files, then it does not make sense to have multiple sections just to show several .java files.

Here is how the metamodel has changed:

* Trivial: "selection" is essentially called "artifact" now.
* Non-trivial: "artifact" ("selection") is of "+" rather than "?" cardinality now.
* Trivial (?): I moved some properties from "projection" to "artifact".

**Comment by rlaemmel** [comment]
Once this issue is fixed, models for #5 and #6 can be fixed.

For instance: https://softlang.github.io/metalib/javaInfluentInternal.html

![image](https://cloud.githubusercontent.com/assets/1208815/26499485/22941af8-4233-11e7-9dac-752d66e4dfc7.png)

That is, classes State and Transition are missing.

**Comment by johanneshaertel** [comment]
The alternative xtext model contains all artifacts but currently the generation into JSON skips them and appends 'Not showing all artifacts' to the headline.

**Comment by rlaemmel** [comment]
Let's not take any dependency on yet another (meta)model or implementation. So we just need JSON-based conformance and rendering to be the correct and only reference implementation :-) I am not going to file issues against other things.

**Comment by sschauss** [comment]
I addressed this issue in 1d23b6515e6385ed4226ada86dd1edf629e8b7bf
